CREATE TABLE uploadList (
  id SERIAL PRIMARY KEY,
  added_by TEXT NOT NULL,
  added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ips CIDR[] NOT NULL
);

CREATE TABLE penalties (
  id SERIAL PRIMARY KEY,
  ip CIDR NOT NULL, 
  source_id INTEGER NOT NULL REFERENCES uploadList(id),
  rating INTEGER NOT NULL DEFAULT 1,
  added_by TEXT NOT NULL,
  added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  roles TEXT[] NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

