CREATE TABLE penalties (
  id SERIAL PRIMARY KEY,
  ip CIDR NOT NULL, 
  team_name TEXT,
  rating INTEGER NOT NULL DEFAULT 1,
  added_by TEXT NOT NULL,
  added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE penalties_summary (
  id SERIAL PRIMARY KEY,
  ip CIDR NOT NULL,
  rating INTEGER NOT NULL,
  added_by TEXT NOT NULL,
  team_name TEXT,
  added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY UNIQUE,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  roles TEXT[] NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE teams (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL REFERENCES users(email),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (name, email)
);

